#
# QuPath conda-forge friendly recipe
#
# Since the JDK situation in conda-forge is at the moment a bit stuck,
# we repackage QuPath releases, including the current JRE used to develop them.
#
# This package allows using QuPath both as a standalone application or pimped
# from python using "ququ", that should be able to automagically find qupath
# when this package is installed.
#

{% set github_version="0.2.2" %}
{% set version="0.2.2" %}
{% set build_number="0" %}

package:
  name: qupath
  version: {{ version }}

source:

  - url: https://github.com/qupath/qupath/releases/download/v{{ github_version }}/QuPath-{{ github_version }}-Linux.tar.xz  # [linux]
    sha256: f61efaba3b18e645c21d71a4f184461c1c698acff3d3674061f76a4d307a3717                                                # [linux]

  - url: https://github.com/qupath/qupath/releases/download/v{{ github_version }}/QuPath-{{ github_version }}-Mac.pkg  # [osx]
    sha256: d99e4966f0e3c4c33c38f14c3c62275ef8f3fcf44fcf902c16d945d15dc8a118                                           # [osx]

  - url: https://github.com/qupath/qupath/releases/download/v{{ github_version }}/QuPath-{{ github_version }}-Windows.zip  # [win]
    folder: qupath                                                                                                         # [win]
    sha256: 668dbdf6840833b3d8c6577fdaf7c2e3759dc27dabf37d19741e56ecfd925dca                                               # [win]

build:

  number: {{ build_number }}

  # See https://conda.io/projects/conda-build/en/latest/resources/define-metadata.html#binary-relocation
  # QuPath is working fine without relocation, but chokes if conda messes around these shared objects
  binary_relocation: False

  script:

    # --- linux
    - mkdir -p ${PREFIX}/opt/QuPath-{{ github_version }}                # [linux]
    - mv bin lib ${PREFIX}/opt/QuPath-{{ github_version }}              # [linux]
    - cd ${PREFIX}/opt                                                  # [linux]
    - ln -s QuPath-{{ github_version }} QuPath                          # [linux]
    - mkdir -p ${PREFIX}/bin                                            # [linux]
    - cd ${PREFIX}/bin                                                  # [linux]
    - ln -s ../opt/QuPath/bin/QuPath-{{ github_version }} ./qupath-bin  # [linux]
    - cp ${RECIPE_DIR}/qupath-linux ${PREFIX}/bin/qupath                # [linux]

    # --- macos
    - 7z x QuPath-{{ github_version }}-Mac.pkg                                      # [osx]
    - 7z x Payload~                                                                 # [osx]
    - mv QuPath-{{ github_version }}.app ${PREFIX}/bin                              # [osx]
    - cd ${PREFIX}/bin                                                              # [osx]
    - ln -s QuPath-{{ github_version }}.app QuPath.app                              # [osx]
    - chmod +x QuPath.app/Contents/MacOS/QuPath-{{ github_version }}                # [osx]
    - cp ${RECIPE_DIR}/qupath-macos ${PREFIX}/bin/qupath                            # [osx]

    # --- windows
    - mkdir %LIBRARY_PREFIX%\QuPath                                                                    # [win]
    - robocopy %SRC_DIR%\qupath\ %LIBRARY_PREFIX%\QuPath\ *.* /E /MOV                                  # [win]
    - copy %LIBRARY_PREFIX%\QuPath\QuPath-{{ github_version }}.exe %LIBRARY_PREFIX%\QuPath\QuPath.exe  # [win]

  # At the moment these are milestones and there are no API stability guarantees.
  # So let's not pin here yet
  # run_exports:
    # - {{ pin_subpackage('qupath', max_pin='x.x') }}

requirements:
  build:
    - p7zip  # [osx]
  run:
    - pixman >0.38.4  # [unix]

test:
  commands:
    # some smoke tests
    - qupath -script fake -image fake.ome.tiff  # [unix]

    # TODO: work some proper tests in windows (when we setup access to a VM or get a windows machine)
    # Notes: using this command here does not work (YAML cannot be parsed)
    #        using it in run_test.bat hangs the test
    # - %LIBRARY_PREFIX%\QuPath\QuPath.exe -script fake -image fake.ome.tiff # [win]
    # So we only check that the files exist in the package...
    - if exist %LIBRARY_PREFIX%\QuPath\QuPath.exe (exit 0) else (exit 1)  # [win]

    # maybe do run some script to exercise the library (e.g. make sure openslide is found and works correctly)
    # maybe install ququ and test some bindings

about:
  home: https://qupath.github.io/
  license: GPLv3
  # TODO probably we should specify license_file with all licenses from qupath deps... they are included anyway in package
  # Maybe copy them as part of the build process (see e.g. the ffmpeg windows recipe)
  summary: QuPath is an open, powerful, flexible, extensible software platform for whole slide image analysis.

extra:
  recipe-maintainers:
    - sdvillal
